name: Build DilSihirbazi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clean previous Theos
        run: |
          rm -rf $HOME/theos

      - name: Install dependencies
        run: |
          brew update
          brew install ldid dpkg git curl

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Install iOS SDKs (official Theos method)
        run: |
          export THEOS=$HOME/theos
          mkdir -p $THEOS/sdks
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make clean
          make package

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: DilSihirbazi.dylib
          path: |
            .theos/obj/**/DilSihirbazi.dylib
